# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk.xci
# IP: The module: 'cnt_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk.xci
# IP: The module: 'cnt_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dengkaixuan/vivado_project/CS202Project/CO_project.srcs/sources_1/ip/cnt_clk/cnt_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
